[feature/mem-optimizations] Optimize memory usage
owncloud/ios-sdk pull request #121
Opened 2024-10-01 09:44 UTC by felix-schwarz

## Description
This PR reduces the memory consumption of the SDK.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2024-10-01 09:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/ios-sdk?pullRequest=121) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/ios-sdk?pullRequest=121) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/ios-sdk?pullRequest=121) it.</sub>

2025-01-21 13:12 UTC, hosy requested changes

2025-01-21 13:12 UTC, hosy commented on ownCloudSDK/Bookmark/OCBookmark.m
> +	[coder encodeObject:_avatarDataURL forKey:@"avatarDataURL"];
```suggestion
if (_avatarDataURL == nil)
	{
		[coder encodeObject:_avatarData forKey:@"avatarData"];
	} else {
		[coder encodeObject:_avatarDataURL forKey:@"avatarDataURL"];
	}
```

Should this only be encoded if `_avatarDataURL ` is not `nil`?

2025-01-22 09:33 UTC, felix-schwarz commented on ownCloudSDK/Bookmark/OCBookmark.m
> +	[coder encodeObject:_avatarDataURL forKey:@"avatarDataURL"];
No, that check is not necessary since [-[NSKeyedArchiver encodeObject:forKey:]](https://developer.apple.com/documentation/foundation/nskeyedarchiver/1412067-encodeobject?language=objc#) allows the passed object to be `nil` and will just not encode an object for that key then.

2025-01-23 16:43 UTC, merged

2025-01-23 16:45 UTC, felix-schwarz commented
@hosy I had to merge this PR in order to resolve merge conflicts in https://github.com/owncloud/ios-app/pull/1430 (which required merging with ios-app/master, which - already having merged the ios-app portion of this PR - in turn requires the SDK changes in this PR). The one finding that turned up during CR was addressed - if there's more to address, please let me know.

2025-01-30 20:06 UTC, felix-schwarz commented
@hosy FWIW I made a small additional change directly in `master` in https://github.com/owncloud/ios-sdk/commit/4f570cab2c1d33b4e43882775fc6f5d8d71c68fe which has a surprisingly huge effect on memory usage (several MBs!)